### ISSUE TITLE
Terraria, Subnautica (Nitrox), etc. not showing up, "Save" option is grayed out when using "Add Service"

### ISSUE THREAD

**Issue by prototype464** [dotStart/Beacon#19]
Some things aren't showing up in Alpha 2 that show in Alpha 1 and adding custom ports doesn't work, though I recall it did work right before updating to Alpha 1 and then updating to Alpha 2 and reverting back to Alpha 1.

**Reproduction Steps**
Describe the steps to reproduce the behavior:
1. Use v3.0.0 Alpha 2.
2. Look at the list of games, some are missing that were added in Alpha 1.
3. Go into "Add Service".
4. Enter in a TCP or UDP port.

**Expected Behavior**
Games tab won't show Terraria, Subnautica (Nitrox), etc.

"Save" should not be greyed out when trying to add custom services/ports.

Reverting back to 3.0.0 Alpha 1 fixes the games not showing problem, though the "Save" issue is still there.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Application Version: v3.0.0 Alpha 2

**Comment by dotStart** [comment]
Make sure to enter a service name within the "Add Service" window. Otherwise saving is not permitted.

**Comment by prototype464** [comment]
Oh, I didn't see that. My bad!
