### ISSUE TITLE
[BUG] Problem with opening ports on Linux

### ISSUE THREAD

**Issue by TerThesz** [dotStart/Beacon#9]
**To Reproduce**
1. Open Beacon.jar
2. Try openning any port
3. An Error

**Expected behavior**
An error should pop out in the console saying- Port mapping registration for *port* has failed

**Screenshots**
![image](https://user-images.githubusercontent.com/60745997/97596762-5a797500-1a05-11eb-9e9d-9784952d23f1.png)

**Environment (please complete the following information):**
 - OS: Raspbian
 - Version 10
 - Application Version 2.2.0

**Comment by dotStart** [comment]
This issue should be resolved in version 2.3.0 through the new UPnP stack.
